/** 常见厨房预勾。覆盖默认可排出餐的主食蛋白蔬菜调味，不是某家店快照。 */
export const COMMON_KITCHEN_IDS = [
  "chicken-breast",
  "egg",
  "pork-loin",
  "pork-belly",
  "firm-tofu",
  "shrimp",
  "white-rice",
  "brown-rice",
  "oats",
  "potato",
  "sweet-potato",
  "wheat-flour",
  "dried-noodles",
  "fresh-noodle",
  "broccoli",
  "tomato",
  "cucumber",
  "carrot",
  "onion",
  "spinach",
  "napa-cabbage",
  "eggplant",
  "green-pepper",
  "shiitake",
  "chinese-celery",
  "olive-oil",
  "peanut-oil",
  "sesame-oil",
  "rapeseed-oil",
  "salt",
  "soy-sauce",
  "dark-soy-sauce",
  "cooking-wine",
  "garlic",
  "ginger",
  "scallion",
  "oyster-sauce",
  "white-vinegar",
  "banana",
  "whole-milk",
  "greek-yogurt",
] as const;

export function commonKitchenIds(): string[] {
  return [...COMMON_KITCHEN_IDS];
}
